name: Build and Deploy
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  docs:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
      - name: 🚀 Build and Deploy
        uses: tlienart/xranklin-build-action@main
        with:
          DEPLOY: ${{ github.event_name == 'push' }}
          BASE_URL_PREFIX: "JuliaIntro"
